const mongoose = require("mongoose");
const schema = mongoose.Schema;

const UserSchema = new schema({
    user_id:{
        type: 'ObjectId',
    },
    first_name:{
        type:String,
        required:true
    },
    last_name:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    province:{
        type:String,
        required:true
    },
    country:{
        type:String,
        required:true
    },
    postal_code:{
        type:Number,
        required:true
    },
    photo:{
        type:String,
        required:true
    },
    credential: {
        user_login:{
            type:String,
            required:true
        },
        user_password:{
            type:String,
            required:true
        },
        mobile_phone:{
            type:String,
            required:true
        },
        is_verified:{
            type:Number,
            required:true
        },
        is_active:{
            type:Number,
            required:true
        },
        verified_code:{
            type:String,
            required:false
        },
        access_token:{
            type:String,
            required:false
        },
        statusid:{
            type:Number,
            required:true
        },
    },
    created_by:{
        type:Number,
        required:true
    },
    modified_by:{
        type:Number,
        required:true
    },
    created_at:{
        type:Date,
        default:Date.now
    },
    modified_at:{
        type:Date,
        default:Date.now
    }
});

module.exports = user = mongoose.model("user",UserSchema);